# ------------------------------
# ----- CONFIGURATION FILE -----
# ------------------------------

# Limits the number of threads, between 4 and 8
max_threads_used: 8

# Limits the number of request, between 1 and 30
max_request: 25

# Limits the number of worker, minimum 1
max_workers: 8

# Time alowed to client to read the response, minimum 0
waiting_time: 10
